### ISSUE TITLE
packaging into jar or aar

### ISSUE THREAD

**Issue by ennoeller** [haibison/android-lockpattern#28]
Hi,

not sure if this is the correct place, but I am having difficulties packaging this library into jar or aar. The problem being than I can not get the resources packaged. I know that typical jar is not supporting resource packaging as default but aar should. The problem in particular is that style.xml is not being packaged, all the strings.xml are. Has anyone succeeded in this or what could I be doing wrong?

Could you provide a jar or aar in the repostiroy?

**Comment by haibison** [comment]
Hello Enno Eller,

Unfortunately for Android library projects which have resources (strings, layouts...), they cannot be bundled into .jar files. So we cannot do nothing about it.

With Gradle build system (used by Android Studio, not Eclipse), there's a short way to include libraries into host project, via remote repositories. This means you need Internet connection whenever you need to compile the project. But again, currently we don't support Gradle build system yet. In the upcoming months we will release the support.

GitHub doesn't support Downloads for projects' assets/releases... So we bundle the source tree in the [demo app](https://play.google.com/store/apps/details?id=group.pals.android.lib.ui.lockpattern.demo). Or you can always clone the source and compile it instead, please remember to replace [symbolic links](http://en.wikipedia.org/wiki/Symbolic_link) with real files, if your system doesn't support symbolic links. Every commit which is stable release is named in this form, for example: `*** RELEASE v3.2 (#45) ***` ([here](https://github.com/haibison/android-lockpattern/commit/2dda221a2bb2b9467b36bb6b395978eb2e8fa8cb)).

Sincerely,
Hai
