### ISSUE TITLE
Setting Image in background

### ISSUE THREAD

**Issue by shantanu1227** [haibison/android-lockpattern#33]
I want to set custom images on the background of the pattern lock. So how can i do that?

**Comment by haibison** [comment]
@shantanu1227 

Currently there's no public APIs to do that. So you have to clone the project to your local machine. Then open these files and set the background for them:

    app/src/main/res/layout/alp_42447968_lock_pattern_activity.xml
    app/src/main/res/layout/alp_42447968_lock_pattern_activity_land.xml

However I don't know how to import the project as a library project from local machine. I'm sorry.
