### ISSUE TITLE
Compare Pattern ISSUE.

### ISSUE THREAD

**Issue by sangharatna** [haibison/android-lockpattern#35]
when call compare pattern activity on that, if  select  single dot then also it compare single dot with the provided pattern.

 want a implementation like , if  set a limit for wired dots as 4 then at compare activity it first check there is 4 dot selected or not.

Problem : when select single dot for 3 time activity get closed.

**Comment by haibison** [comment]
I'm sorry, I don't care about grammar, but I do hate it when people use `i`. Please fix the `i`, then I'll try to help.

Reference: [I (pronoun)](https://en.wikipedia.org/wiki/I_(pronoun)).

**Comment by sangharatna** [comment]
@haibison  we are here for development , not for the English grammar improvement.

if you get what people want to say, then its enough. no matter how bad grammar he/she used.

**Comment by haibison** [comment]
Then sorry, I can't help.
