### ISSUE TITLE
Custom pattern theme

### ISSUE THREAD

**Issue by AlexGascon** [haibison/android-lockpattern#36]
Hi! 

I'm integrating this library in my app, and I would like the pattern to match my app theme's colors. However, when I try to create a custom theme using some of your default themes as parent, it doesn't override the "alp_42447968" elements, only allowing me to modify the "android:" ones (such as background).

Is there any way to create a custom theme that allows me to change those elements?

Here's the code of my style in case its useful 

```
    <style name="Pattern.Theme.Authentic" parent="Alp_42447968.Theme.Light">
        <item name="android:background">@color/ColorPrimary</item>
        <item name="alp_42447968_color_lock_pattern_view_success">@color/ColorAccent</item>
        <item name="alp_42447968_color_lock_pattern_view_regular">@color/white</item>
        <!-- AOSP -->
    </style>
```

Thank you so much in advance for your help

(Sorry if this isn't an appropiate question. I'm an Android begginer)

**Comment by haibison** [comment]
Hi Alex,

There are 2 steps:

1. Please make one group of resources, it just contains resources from the library (the ones start with `alp_42447968_`). Then you can define your overridden resources from within that group. If you just override some items, you should make that group inherit one of available theme resources, for example `Alp_42447968.ThemeResources.Light`.

2. From your new theme, pass that group via attribute `alp_42447968_theme_resources`.

You can see some example in [`styles.xml`](https://github.com/haibison/android-lockpattern/blob/master/app/src/main/res/values/styles.xml), such as this couple: `Alp_42447968.ThemeResources.Light` and `Alp_42447968.Theme.Light`.

Have a nice day  :-)

**Comment by AlexGascon** [comment]
Ok, I got it now! Thank you so much and have a nice day too! :)

**Comment by haibison** [comment]
You're welcome, hope you enjoy the library  :-)
