### ISSUE TITLE
A lite advice about IEncrypter

### ISSUE THREAD

**Issue by MiyamuraMiyako** [haibison/android-lockpattern#41]
```java
public List<LockPatternView.Cell> decrypt(Context context, char[] chars)
```
Why decrypt method only provide ```char array```?

I think should be provide ```List<LockPatternView.Cell> (user input pattern)``` and ```char array (encrypted pattern)```, and return ```boolean```. Because after the password encryption should not be able to reverse operation. Just like the following:
```java
public boolean decrypt(Context context,  List<LockPatternView.Cell> list, char[] chars)
```

**Comment by haibison** [comment]
Hi Miyako,

It's because I don't really understand encryption, my bad  :-(

If it's easy to explain, would you please help? If it's hard to explain, and you know of some documentation online, please send me the links so I can learn.

**Comment by MiyamuraMiyako** [comment]
OK, I fork this project and just change minimal code.

```Password can not be inverse operation, generally, the password is stored in the hash value, such as SHA1, SHA256, etc.Otherwise, others people get to the password file will be able to obtain the password inverse.```

Usage example:
```java
public class LockPatternEncrypter implements IEncrypter
{
    @Override public char[] encrypt(Context context, List<LockPatternView.Cell> list)
    {
        //Do some irreversible encrypt operate.
        return doEncrypt(list);
    }

    @Override public List<LockPatternView.Cell> decrypt(Context context, List<Cell> pattern, char[] chars)
    {
        char[] input = doEncrypt(list);
        return Arrays.equals(input, chars);
    }
}
```
my repo address: (fork project)[https://github.com/MiyamuraMiyako/android-lockpattern]
If you think this change is acceptable, then I pull request to you.

**Comment by haibison** [comment]
Thank you,

However I already used that approach before moving to current one.

---

Using encryption can encrypt one same phrase to different phrases, via salt. For example with [`SimpleWeakEncryption`](http://haibison.github.io/android-lockpattern/apidocs/haibison/android/lockpattern/util/SimpleWeakEncryption.html), `A` is input string, password is `B`, salt is `null`, call `encrypt()` 2 times we'll get 2 different encrypted strings:

- `-ld4lkkipae8wdf3al8uj8w0s@-6zkytz4tyktmqskesr9ha2b8y`
- `-5tkyqn6t8zer7ilxperpfp5ee@61wloyv04eeajd5hev3r36ab8`

However using checksum like SHA1, SHA256... can only deliver one unique result, for instance SHA1 of `A` will always be `6dcd4ce23d88e2ee9568ba546c007c63d9131c1b`.

---

So I think the approach with encryption would be better than calculating checksum.

**Comment by MiyamuraMiyako** [comment]
Yes, add salt can generate different hash. My app used salt too.

Interesting, ```SimpleWeakEncryption``` not implement ```IEncrypter```, How it work?

**Comment by haibison** [comment]
I'm sorry for the delay. `SimpleWeakEncryption` is just a tool which helps encrypt/decrypt strings. While `IEncrypter` is another interface which is used by `LockPatternActivity`. For instance, developers can implement their own better encryption tool (instead of `SimpleWeakEncryption`), and use it in `IEncrypter`.

**Comment by MiyamuraMiyako** [comment]
It doesn't matter.

So,I think this issue can be close,right?

**Comment by haibison** [comment]
I'm closing it. Have a nice day  :-)
